name: check91
version: 1.0.10
summary: Flutter Demo check91 Application
description: A demo of check91 Application using Flutter
confinement: strict
base: core20
grade: stable
icon: snap/gui/icon.png


apps:
  check91:
    command: check91-app
    extensions: [flutter-master]
    plugs:
      - network
      - desktop

parts:
  check91:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application